### ISSUE TITLE
Request timing out

### ISSUE THREAD

**Issue by mikedfunk** [zbirenbaum/copilot.lua#2] opened 2022-04-04 22:44 UTC
![image](https://user-images.githubusercontent.com/661038/161644300-f549f5ef-9acb-4f13-8573-182196b650d2.png)

**Comment by mikedfunk** [comment] 2022-04-04 22:44
Related: #1

**Comment by mikedfunk** [comment] 2022-04-04 22:45
`curl: no URL specified!`

I think it's a problem with how plenary is called?

**Comment by zbirenbaum** [comment] 2022-04-04 22:51
> `curl: no URL specified!`
> 
> I think it's a problem with how plenary is called?

Just to try and isolate any issues: Don't post a photo but can you try the following:
`nvim ~/.local/share/nvim/site/pack/packer/opt/copilot.lua/lua/copilot/setup.lua`
and add a line: `print(token)` to
```
local function oauth_user(token)
   print(token)
   local response = request({
      url = "https://api.github.com/user",
      headers = {
         Authorization = "Bearer " .. token,
      },
   })
   return json_body(response)
end
```
If when you restart neovim it prints some string, that means it's working properly and something else is the problem.

I'm going to take a look in plenary's code base. My gut reaction is that osx likely uses a curl version that parses arguments differently than linux for some reason, as the url is clearly defined here

**Comment by zbirenbaum** [comment] 2022-04-04 23:03
@mikedfunk Just pushed an update which makes the request using curl and a system call directly. Let me know if it works.

**Comment by mikedfunk** [comment] 2022-04-04 23:05
nope

![image](https://user-images.githubusercontent.com/661038/161646610-b877c740-9453-42c9-99eb-9c7fccd7b775.png)

**Comment by zbirenbaum** [comment] 2022-04-04 23:06
Can you run the following command in a terminal: 
curl --header "Authorization: Bearer  <token>" https://api.github.com/user

where <token> is the token in the hosts file in .config/github-copilot

**Comment by mikedfunk** [comment] 2022-04-04 23:09
![image](https://user-images.githubusercontent.com/661038/161646968-f7c54801-dc98-4a76-9359-35319d0b09cf.png)

But `:Copilot setup` still returns

![image](https://user-images.githubusercontent.com/661038/161647015-5d803a85-9db7-4217-abd8-6effe35769fc.png)

**Comment by zbirenbaum** [comment] 2022-04-04 23:11
@mikedfunk You forgot a ':' after Authorization. Does copilot.vim work for you? There's a weird glitch where invalid api keys will claim to work with copilot.vim but the requests for auth don't go through.

**Comment by mikedfunk** [comment] 2022-04-04 23:14
Ah, oops, works fine with the `:`.

Yes, copilot.vim was working for me mostly, but it was clobbering some other useful `cmp` sources like `cmp-tmux` and sometimes the lsp source for some reason. That's why I disabled it.

**Comment by zbirenbaum** [comment] 2022-04-04 23:16
Yeah that's my issue with it too. We'll get this working for you, making progress here. Now try it with the -s flag, see if you get the same output minus the 'downloading' metadata at the top.
`curl -s --header "Authorization: Bearer <token>" https://api.github.com/user`

**Comment by mikedfunk** [comment] 2022-04-04 23:18
works as well

**Comment by zbirenbaum** [comment] 2022-04-04 23:20
Ok, in the same file as before try changing:
```
local function oauth_user(token)
   return vim.fn.json_decode(vim.fn.system("curl -s --header \"Authorization: Bearer " .. token .. "\" https://api.github.com/user"))
end
```
to this:
```
local function oauth_user(token)
   local response = vim.fn.system("curl -s --header \"Authorization: Bearer " .. token .. "\" https://api.github.com/user")
   local tbl = vim.fn.json_decode(response)
   print(response)
   print(vim.inspect(tbl))
   return tbl
end
```

For some more debug output

**Comment by mikedfunk** [comment] 2022-04-04 23:44
I'll get back to this later, got work to do

**Comment by zbirenbaum** [comment] 2022-04-04 23:46
> I'll get back to this later, got work to do

Sounds good. Maybe someone else can reproduce it in the meantime. Sorry for the trouble, and thanks for the help debugging.

**Comment by zbirenbaum** [comment] 2022-04-07 18:20
Is this still and issue or should I close it? I haven't seen anyone reproduce it over the past few days. Did you ever figure it out?

**Comment by zbirenbaum** [comment] 2022-04-09 00:16
Your issue should be fixed. This whole step was able to be removed since it apparently can be handled by the copilot server. I'll reopen this if I end up having to add the auth back for some reason.

**Closed by zbirenbaum** 2022-04-09 00:16 UTC

**Comment by mikedfunk** [comment] 2022-04-20 02:50
Ah sorry, I'll try it again when I get the chance.
