### ISSUE TITLE
Client x quit with exit code ...

### ISSUE THREAD

**Issue by wlamers** [zbirenbaum/copilot.lua#35] opened 2022-06-20 14:19 UTC
Really like the idea to have copilot in cmp. But I keep getting the error message: 'Client 1 quit with exit code 1 and signal 0', whatever config setup I try. The regular copilot.vim plugin works fine. Any way I could debug this or get more verbose output of the error?

**Comment by zbirenbaum** [comment] 2022-06-20 14:22
Could you provide the full error output, along with screenshots of your :LspStatus and :CmpStatus 

It may also be helpful to know which version of neovim you are using. Please check your :LspLog as well to see if copilot returns an authentication error

**Comment by zbirenbaum** [comment] 2022-06-20 14:27
Sorry nevermind this was likely caused by something I merged from this morning. I rolled it back, please PackerSync and try it again.

**Comment by zbirenbaum** [comment] 2022-06-20 14:29
Yeah this is definitely from the change I made this morning. I didn't get the same error message but it broke for me too. You may have to manually rm -rf ~/.local/share/nvim/site/pack/packer/opt/copilot.lua in order for packer to download the reverted version

**Comment by wlamers** [comment] 2022-06-20 14:38
Haha we crossed each other. But working now! Thx!

**Closed** 2022-06-20 14:39 UTC
