### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by Gako358** [zbirenbaum/copilot.lua#13] opened 2022-04-08 08:01 UTC
![copilot6](https://user-images.githubusercontent.com/42249650/162391931-3d367fda-3448-4fa3-b76f-f3640087a254.png)

I did a full rebuild of my nvim, deleted all and then installed as you have described, and still getting this,
You also closed my other ticket, without addressing my issue, that was just like this.

https://github.com/Gako358/Dotfiles/tree/205e79501493609aeba5954583a53e5dc4e4fea6/.config/nvim
My nvim config, if you want to add and see if you can make it work

**Comment by zbirenbaum** [comment] 2022-04-08 09:14
I believe your other issue was #10. That appears very different to me than this. This error message actually tells me almost exactly what the problem is!

I believe the issue is in your ~/.config/github-copilot/hosts.json file. If copilot.vim works, then the file is valid, but maybe some token in there is causing a problem or something. Its extremely early here (about 5am) but tomorrow I can make a branch or something that you can use to try and debug without showing anything private.

**Comment by zbirenbaum** [comment] 2022-04-08 09:26
If you want to try and debug this yourself in the meantime, open up a lua file and put the relevant code in there:
```
local function oauth_user(token)
  return vim.json.decode(
    vim.fn.system('curl -s --header "Authorization: Bearer ' .. token .. '" https://api.github.com/user')
  )
end

local get_cred = function()
  local userdata = vim.json.decode(
    vim.api.nvim_eval("readfile('" .. find_config_path() .. "/github-copilot/hosts.json')")[1]
  )
  local token = userdata["github.com"].oauth_token
  local user = oauth_user(token)
  return { user = user, token = token }
end

get_cred()
```

Then just run the file with `:luafile %` while you have it opened after saving, add some print statements or print(vim.inspect())'s and you should find your issue within about 5 min. Since I can't reproduce it, its going to be hard to figure this out on my end.

**Comment by Gako358** [comment] 2022-04-08 12:53
I am on Gentoo, but not aware anything different from other users..?

**Comment by zbirenbaum** [comment] 2022-04-08 17:54
> I am on Gentoo, but not aware anything different from other users..?

It should be working fine on Gentoo. Did you try isolating the issue with the code I provided? The error message you gave makes it pretty clear the error is somewhere in there, so running that snippet in isolation should reproduce the issue.

**Comment by Gako358** [comment] 2022-04-08 18:23
Ive been trying a bit and I hardcoded my path to copilot folder, and printed to confirm location. Correct location. Then I printed vim.inspect(userdata) and the information is correct according to my hosts.json file.

But still getting error..
and the funny thing is, on each run it changes that value that is invalid

```
Error while calling lua chunk: test.lua.36: Expected value but found invalid token at character 16
```

The token character changes on each run...

**Comment by zbirenbaum** [comment] 2022-04-08 22:14
> Ive been trying a bit and I hardcoded my path to copilot folder, and printed to confirm location. Correct location. Then I printed vim.inspect(userdata) and the information is correct according to my hosts.json file.
> 
> 
> 
> But still getting error..
> 
> and the funny thing is, on each run it changes that value that is invalid
> 
> 
> 
> ```
> 
> Error while calling lua chunk: test.lua.36: Expected value but found invalid token at character 16
> 
> ```
> 
> 
> 
> The token character changes on each run...

This error occurs on the json_decode line for curl correct? Try moving the curl result to a variable outside of the decode. Then print it using vim.inspect, when it errors you should be able to tell where. I would run it twice to see if the string itself that's being decoded changes, or if it's just the order of the response components.

**Comment by zbirenbaum** [comment] 2022-04-09 00:15
I am 99.99% certain your issue is fixed as of the latest patch. I randomly reproduced your problem, and although I could do so only once, I was able to find out that this is an upstream issue related to unicode characters.

I found out in further testing, that copilot still apparently functions with no authentication step whatsoever, as long as hosts.json exists. I think the 20 something thousand line javascript file takes care of auth if you don't pass parameters to it. When reverse engineering said file, it appeared that you needed to give it the variables I had set in the environment, but apparently it will resolve them for you if not provided.

Thus, all authentication has been removed until I fully implement the steps from copilot.vim, so that this is a total replacement. Even then, if you already have a hosts.json you should be ok, since I would have a check for it before requiring auth.

**Closed** 2022-04-09 00:16 UTC

**Comment by zbirenbaum** [comment] 2022-04-09 00:44
I closed this since the entire body of code that has been giving you problems is no longer called, but if you are not getting completions still (I strongly hope and doubt this will be the case), that will be a problem and we may have to readdress this, so feel free to reopen it.
